//
// Created by sterr on 31-7-2022.
//

#ifndef ENTITY_COMPONENT_SYSTEM_TEST_ENTITYMANGER_H
#define ENTITY_COMPONENT_SYSTEM_TEST_ENTITYMANGER_H


class EntityManger {

};


#endif //ENTITY_COMPONENT_SYSTEM_TEST_ENTITYMANGER_H
